version: '3.9'  
  
services:
  db:
    image: mysql:8.0.33-debian
    volumes:
        - ./database/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=projeto_ru_django
    networks:
      - compose_network
    ports:
      - "25565:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  web:
    build: ./projeto-ru
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./projeto-ru:/code/
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=projeto_ru_django
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - compose_network

networks:
  compose_network: